### ISSUE TITLE
Shell command from other buttons (T'eyes CC3) ?

### ISSUE THREAD

**Issue by noenic** [hvdwolf/FytHWOneKey#10]
Hi, your app is a true gift from God, I had no possibility to open carplay from one of these buttons, thanks to you now I can.

But I still have one last thing to figure out, when I press the voice button (setup as EQ button)l, it opens the voice assistant of teyes that is good for nothing. Is there a way to instead of opening the teyes voice application this key calls the siri function of the Carlink 2.0 application? I don’t know the keys this application is able to recognize but it seems weird that the voice control buttons are not detectable but others like play/pause and next/previous are working

thanks

**Comment by hvdwolf** [comment]
Someone mentioned [here](https://forum.xda-developers.com/t/fyt-units-fythwonekey-non-rooted-app-to-assign-other-apps-to-the-unit-hardware-buttons.3912075/page-10#post-87166995) that a Russian modder modified the original steering app.

See also [this post](https://forum.xda-developers.com/t/fyt-units-fythwonekey-non-rooted-app-to-assign-other-apps-to-the-unit-hardware-buttons.3912075/page-9#post-87161633) to contact the guy who paid that Russian modder.

**Comment by noenic** [comment]
Wow, it sucks, we pay for android units a fortune and in the end we get blocked by the system. The default application of the steering wheel buttons is completely messed up.

But I thought of something, your application allows you to change the name of the packet when you press the voice button. In this settings you can only link a new package name. But if we could do as for the option BAND or DVD put a SHELL command with the command "input keyevent 231" supposed to open the voice assistant. I have not yet tested with adb what would be the result of this order on my device. In case carkit listens to this key, do you think it would work?

But is there a reason that you can’t put a shell command option to each parameter button instead of just the BAND or DVD button?

thank you

**Comment by hvdwolf** [comment]
You can put a shell command there and also an intent.
You have 3 options: package name, intent, external command.
First select the first option being the Call method.
![Screenshot_20220727-140704](https://user-images.githubusercontent.com/4520361/181243776-70682130-43b8-45d1-aab6-f50856a66103.png)

And when you have pressed "Band key: call method", you can select out of the 3 options
![Screenshot_20220727-140716](https://user-images.githubusercontent.com/4520361/181244041-7022acc8-b08b-4357-8d38-58923f96aff7.png)

Not only that: it is fully described in the Readme.

**Comment by noenic** [comment]
No, I mean it's only available in the BAND and DVD menu. (I already using the BAND for my radio, and I don't have any DVD button in the steering wheel app)

![Capture d’écran 2022-07-27 142624](https://user-images.githubusercontent.com/75330764/181247471-881bc5e1-95eb-4a4b-af53-5b9bd2c52903.png)
![Capture d’écran 2022-07-27 142956](https://user-images.githubusercontent.com/75330764/181247483-43e047eb-3e34-4222-a590-cbdb15734240.png)
![Capture d’écran 2022-07-27 143107](https://user-images.githubusercontent.com/75330764/181247491-00cc1dfe-1b8d-4cb8-b83a-e1b3d0fc3dea.png)

is there a reason why there is no intent and command line method in the other buttons ?

**Comment by hvdwolf** [comment]
No reason at all.
You are the first to ask. I built it as I also had that in my Xposed modules, but when I released it nobody was interested. it is really simple to copy & paste it. I will have a look

**Comment by noenic** [comment]
I tried to connect to the device with ADB but it never managed to get detected. I know that the ADB connection works on my computer because I was able to try the command on my android TV successfully. So I couldn’t try the command on the CC3. 

Yet I enabled USB debugging in the developper options. even windows doesn’t detect anything. Is this something normal on FYT models?

**Comment by hvdwolf** [comment]
Check the [XDA FYT forums](https://forum.xda-developers.com/f/fyt-android-head-units.12445/).
There is so much info there which I won't repeat in this issue as it is off-topic.

**Comment by noenic** [comment]
Okay... After several hours of going around in circles, I finally gave in and I guess there is no button to activate the Siri function. 

In the meantime I finally managed to access adb (wirelessly) and I came up with a solution that is completely awful and I'm not proud of it. But it works. 

simulate a long press on the carplay screen to trigger Siri, not the best idea. but still safer than looking on the screen where to press while driving.

`var=$(dumpsys activity recents | grep 'Recent #0' | cut -d= -f2 | sed 's| .*||' | cut -d '/' -f1) ; if [ $var == 'com.syu.carlink' ]; then input touchscreen swipe 20 600 20 600 900; else echo Not in carlink; fi`

I have the command but I still have no way to test it other than adb because I don't have the run in shell option from the other buttons in your app and i don't have the two buttons BAND and DVD.

**Comment by hvdwolf** [comment]
Started working on making the BAND button functionality for all buttons. Probably this weekend.

**Comment by hvdwolf** [comment]
Please try this new 1.60: https://mega.nz/file/RFtnkD6b#VbE533uNFQE7GvNwuOJauzBXCz_ElryTZf8rgE6Fwts
As I don't have buttons on my unit anymore I can hardly test.

**Comment by noenic** [comment]
Hi ! So I tested the version 1.60 that you sent. and for some reason it doesn't seem to work

https://user-images.githubusercontent.com/75330764/181801333-c9cb7eda-1fa6-40eb-8f45-934e7a8bd077.mp4

I can start app from the package name but it doesn't seem to execute the command, something is clearly happening since carlink flickers (probably it turns into a black screen when the app is not in the foreground)

EDIT: it happens no mater the shell command, I tried "input keyevent 3 "and same thing

**Comment by noenic** [comment]
it seems that the call option has no effect and it still tries to launch it by package name



https://user-images.githubusercontent.com/75330764/181807928-e988a646-27a6-4a76-823e-4111926c9d85.mp4

**Comment by hvdwolf** [comment]
I see. I will have a look at it agan this weekend.

**Comment by hvdwolf** [comment]
It is a bug in the BAND functionality, but as I now copy & pasted it, it is now a bug for every key. 
As it was not a 100% copy & paste, it is now manually a lot of repair work.

**Comment by hvdwolf** [comment]
And now a complete restructure. Please test.
https://mega.nz/file/QEUFzTyA#Uyg8xU4rhnDVEHRG7e7OLDbvJUH2nyjiO8gHvdGqLDc

**Comment by noenic** [comment]
Unfortunately it seems that it still doesn't work, the commands are executed, "reboot" restarts the device well, but the other commands like "input keyevent" don't work, difficult to explain and to see on the video. but when you press the button it looks like the screen freezes in front of a transparent 

the command should open the voice assistant. In ADB shell on my computer it works without any weird screen hanging

https://user-images.githubusercontent.com/75330764/181915563-fc575b23-5c25-4001-bd1d-9c7cfa90ca86.mp4

**Comment by noenic** [comment]
Hi, I may have found a simpler solution.  I created a script on Termux that interacts with adb and does all the commands I want.

I have read about the Termux intent (still quite complicated to understand) and I managed to make it work on another application (key mapper) but on yours I have a little trouble here is the command in shell :

am startservice --user 0 -n com.termux/com.termux.app.RunCommandService \
-a com.termux.RUN_COMMAND \
--es com.termux.RUN_COMMAND_PATH '/data/data/com.termux/files/home/scripts/adb_swipe' \
--ez com.termux.RUN_COMMAND_BACKGROUND 'true' 


in termux it does exactly what I want, how should I write it in your app ? 

Thanks

**Comment by hvdwolf** [comment]
I don't know. I spent quite some time on it this weekend and I simply can't make it work. I know it worked in older versions, but that was on the PX5 (Android 8.0) and the sc9853i (Android 8.1). Maybe the Android 10 is now behaving differently due to increased securty measures, but I actually don't know and I can't find it either on Google or the Android Dev site.
It is also a complete mystery for me.

**Comment by noenic** [comment]
To be honest, I don't understand much about java or android at the moment. Probably this year we'll see it in more detail at my computer science university. But I found some documentation about the Termux app and its possible calls.
I don't know if you have already looked at it: 

[RUN_COMMAND-Intent](https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent)
[Termux Tasker](https://github.com/termux/termux-tasker)

**Comment by noenic** [comment]
I fly totally blind, not understanding anything about java or android studio, but with the documentation I managed to test how to send intents. I don't know if it works on other devices than the android studio emulator because I don't even know how to export the apk without errors when I install it in another machine ahaha


https://user-images.githubusercontent.com/75330764/183245963-a885ff5c-d917-4438-9a16-24a8c58286bd.mp4


```
                Intent intent = new Intent();
                intent.setClassName("com.termux", "com.termux.app.RunCommandService");
                intent.setAction("com.termux.RUN_COMMAND");
                intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/home/test");
                intent.putExtra("com.termux.RUN_COMMAND_BACKGROUND", true);
                intent.putExtra("com.termux.RUN_COMMAND_SESSION_ACTION", "0");
                try{
                    startForegroundService(intent);
                    Snackbar.make(  ̶v̶i̶e̶w̶ , "intent sent", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();}
                catch (Exception e) {
                    Snackbar.make(  ̶v̶i̶e̶w̶ , e.getMessage(), Snackbar.LENGTH_LONG)
                            .setAction("Action", null).show();

```


 
 
 
 
 
 
 
 
 
 





EDIT : I managed to integrate it to the existing FytHWOneKey application, I installed it on my head unit and miracle it works! For the moment it opens only termux it's not great but it's just a question of interface to be able to put the arguments that we want.
I haven't found any other alternative to execute shell commands directly and it's still not perfect  


https://user-images.githubusercontent.com/75330764/183263832-7173ff38-1357-43d2-b3bf-14cf3b2ab0b9.mp4

**Comment by gzsrdfhxrsd** [comment]
Hello, it seems to me that the DVD buttons and the EQ button are generally useless in the application, instead of them there should be other buttons such as: aux, src, settings, voice control, 360, video, in order to be able to hang a specific application on them.  Sorry for my English.

**Comment by hvdwolf** [comment]
If you have a 7" or 8" unit, you have hardware buttons including an EQ button. Some units also have built-in DVD players with a DVD-button. My PX5 did have that.

I will not further develop this app. My last 2 units don't have buttons so my app is completely useless for myself.
It is open source, so you can continue to develop it.

**Comment by hvdwolf** [comment]
> EDIT : I managed to integrate it to the existing FytHWOneKey application, I installed it on my head unit and miracle it works! For the moment it opens only termux it's not great but it's just a question of interface to be able to put the arguments that we want.
> I haven't found any other alternative to execute shell commands directly and it's still not perfect

I think you did a great job, but this is really for your specific case. Some other terminal apps support the same, but of course with different call mechanisms. 
However, it should not be necessary. So far it worked on Android 8.1 and below. Like said: I have no idea whether this is a new security policy in Android and I can't find it either.

Like also mentioned in above post: I will not further develop this app. My last 2 units don't have buttons so my app is completely useless for myself.
It is open source, so you can continue to develop it.

**Comment by noenic** [comment]
> Hello, it seems to me that the DVD buttons and the EQ button are generally useless in the application, instead of them there should be other buttons such as: aux, src, settings, voice control, 360, video, in order to be able to hang a specific application on them. Sorry for my English.

I think the application just uses the same package name as the unit. So you just have to create a new fake package name linked to the application. I don't know how to do it but looking in the source code I think we can find it, for the moment my problem is to integrate it in the GUI 



> I think you did a great job, but this is really for your specific case. Some other terminal apps support the same, but of course with different call mechanisms.
> However, it should not be necessary. So far it worked on Android 8.1 and below. Like said: I have no idea whether this is a new security policy in Android and I can't find it either.

I think that with the last version of android the security concerning the shells commands have been secured.
Some command like "reboot" still works but you can't expect much from "sh", only solution I think would be to root the device.
For the moment, I've worked around the problem by using the run in the background service of termux and it works pretty well, since it works I haven't touched the code too much even if it's far from being optimal


> Like also mentioned in above post: I will not further develop this app. My last 2 units don't have buttons so my app is completely useless for myself.
> It is open source, so you can continue to develop it.

No problem, thanks a lot for the help and for the application, if one day I have the time and the desire I will make a fork fixing the intent option and adding the work around of termux to launch terminal scripts
