### ISSUE TITLE
Xtrons Qualcomm

### ISSUE THREAD

**Issue by danndan23** [hvdwolf/FytHWOneKey#13]
Hello,

Any change that this works for xtrons head units with Qualcomm 665? For example, IQ92MTVL.

Thank you.

**Comment by hvdwolf** [comment]
No, sorry. It has been completely build for the fYT units only. I have no idea how the MTC units do this, but there used to be a likewise program whichs works on a rooted unit with XPosed. I don't know if it still works and I can't remember  the name.
Please search the MTCx forums on https://forum.xda-developers.com/c/head-units.3833/
